Fix build failed about image dose not have an alt attribute
For the Images check, the following failures were found:
* At _site/posts/MISC-DebugUEWithVSCode/index.html:1:
  image /assets/images/DebugUEInVSCode-1-CreateProject.png does not have an alt attribute
* At _site/posts/MISC-DebugUEWithVSCode/index.html:1:
  image /assets/images/DebugUEInVSCode-2-BinaryConfiguration.png does not have an alt attribute
* At _site/posts/MISC-DebugUEWithVSCode/index.html:1:
  image /assets/images/DebugUEInVSCode-3-PackageProject.png does not have an alt attribute
* At _site/posts/MISC-DebugUEWithVSCode/index.html:1:
  image /assets/images/DebugUEInVSCode-4-SetPackagePath.png does not have an alt attribute
* At _site/posts/MISC-DebugUEWithVSCode/index.html:1:
  image /assets/images/DebugUEInVSCode-5-PackagePath.png does not have an alt attribute
* At _site/posts/MISC-DebugUEWithVSCode/index.html:1:
  image /assets/images/DebugUEInVSCode-6-BinaryPath.png does not have an alt attribute
* At _site/posts/MISC-DebugUEWithVSCode/index.html:1:
  image /assets/images/DebugUEInVSCode-7-BeforeSetLaunch.png does not have an alt attribute
* At _site/posts/MISC-DebugUEWithVSCode/index.html:1:
  image /assets/images/DebugUEInVSCode-8-AfterSetLaunch.png does not have an alt attribute
* At _site/posts/MISC-DebugUEWithVSCode/index.html:1:
  image /assets/images/DebugUEInVSCode-9-SelectLaunchProgram.png does not have an alt attribute
HTML-Proofer found 9 failures!
Error: Process completed with exit code 1.