Fix build failure caused by 'a' tag is missing a reference
For the Links check, the following failures were found:

* At _site/posts/LearnOpenGL-AdvancedLighting-AO-SSAO/index.html:497:

  'a' tag is missing a reference

HTML-Proofer found 1 failure!
Error: Process completed with exit code 1.